name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    #Configures the job to run on the latest version of an Ubuntu Linux runner.
    #This means that the job will execute on a fresh virtual machine hosted by GitHub.
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
