name: Run Python Script
# You may pin to the exact commit or the version.
# uses: jannekem/run-python-script-action@4a15c914fc5c168c5fd388e3ded9919af522c175
on:
  workflow_dispatch
jobs:
  run-job-on-demand-example:
    #Configures the job to run on the latest version of an Ubuntu Linux runner.
    #This means that the job will execute on a fresh virtual machine hosted by GitHub
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: jannekem/run-python-script-action@v1.6
        with:
          # Python script
          script: ./Plot_example.py
          # Fail step if the return code from running the script is non-zero
          #fail-on-error: # optional, default is true
          # Include utility functions
          #util: # optional, default is true
          

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

#name: Python application

#on:
 # workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

#permissions:
#  contents: read

#jobs:
#  build:

 #   runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.10"
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install flake8 pytest
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pytest
